services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api